services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka

  eureka:
    build: ./eureka
    ports:
      - "8761:8761"

  job-service:
    build: ./job-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - postgres

  company-service:
    build: ./company-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - postgres

  review-service:
    build: ./review-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: spring_boot_api_tutorial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
