services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    networks:
      - microservice-network

  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  job-service:
    build: ./job-service
    depends_on:
      - eureka
      - postgres
    networks:
      - microservice-network

  company-service:
    build: ./company-service
    depends_on:
      - eureka
      - postgres
    networks:
      - microservice-network

  review-service:
    build: ./review-service
    depends_on:
      - eureka
      - postgres
    networks:
      - microservice-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: spring_boot_api_tutorial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservice-network

volumes:
  postgres-data:

networks:
  microservice-network:
    driver: bridge
